export const SET_MENU_ITEM_NEXT_TOKEN = "SET_MENU_ITEM_NEXT_TOKEN";
export const CLEAR_MENU_ITEM_PAGINATION = "CLEAR_MENU_ITEM_PAGINATION";

export const OPEN_MENU_ITEM_FORM_MODAL = "OPEN_MENU_ITEM_FORM_MODAL";
export const CLOSE_MENU_ITEM_FORM_MODAL = "CLOSE_MENU_ITEM_FORM_MODAL";
