export const OPEN_RESTAURANT_FORM_MODAL = "OPEN_RESTAURANT_FORM_MODAL";
export const CLOSE_RESTAURANT_FORM_MODAL = "CLOSE_RESTAURANT_FORM_MODAL";

export const OPEN_MENU_ITEM_FORM_MODAL = "OPEN_MENU_ITEM_FORM_MODAL";
export const CLOSE_MENU_ITEM_FORM_MODAL = "CLOSE_MENU_ITEM_FORM_MODAL";
