export const SET_RESTAURANT_NEXT_TOKEN = "SET_RESTAURANT_NEXT_TOKEN";
export const CLEAR_RESTAURANT_PAGINATION = "CLEAR_RESTAURANT_PAGINATION";

export const OPEN_RESTAURANT_FORM_MODAL = "OPEN_RESTAURANT_FORM_MODAL";
export const CLOSE_RESTAURANT_FORM_MODAL = "CLOSE_RESTAURANT_FORM_MODAL";
